on: ['push']


jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: run python
        run: python main.py
      - name: catty
        id: step1
        run: |
          contents=$(cat test.txt)
          echo $contents
          echo "::set-output name=test::$contents"
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{ needs.job1.outputs.output1 }}
        