on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'
      isprod:
        description: 'Is this a production deployment?'
        required: true
        default: false
        type: booleans


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: echo "Hello World ${{inputs.environment }}"
      - name: setoutput
        run: echo "::set-output name=boobs::boobs"
      - name: echo boobs
        run: echo "${{ steps.setoutput.outputs.boobs }}""
