name: Shell Commands

on: [push]


jobs:
    run-shell-command:
        runs-on: ubuntu-latest
        steps:
            - name: echo a string
              run: echo "Hello World"
            - name: save state
              run: echo "::save-state name=boobs::boobs"
            - name: output
              run: echo "::set-output name=boobs::boobs"
    second-shall-command:
        runs-on: ubuntu-latest
        steps:
            - name: echo a string
              run: echo "second World"
            - name: access state
              run: echo "::set-output name=boobs::boobs" 

    blank:
        runs-on: ubuntu-latest
        steps:
            - name: ml
              run: |
                node -v
                npm -v
