on: ['push']


jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
    steps:
      - name: step1
        id: step1
        run: echo "test=wag1, lkmlkm=ookkm" >> $GITHUB_OUTPUT


  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: step2
        run: echo ${{ needs.job1.outputs.output1 }}
      - name: step3
        id: step3
        run: echo "wagenv=wag1" >> $GITHUB_ENV
      - name: step4
        id: step4
        run: echo "${{env.wagenv}}"
  
    