on: ['push']


jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
    steps:
      - name: step1
        id: step1
        run: echo "test=hello" >> $GITHUB_OUTPUT


  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: step2
        run: echo ${{ needs.job1.outputs.output1 }}
    